language:
    - cpp

before_install:
    - pip install --user cpp-coveralls

branches:
    except:
        - gh-pages

env:
    global:
        - GH_REPO_NAME: Snoke
        - DOXYFILE: "$TRAVIS_BUILD_DIR/Doxyfile"
        - GH_REPO_REF: github.com/echo-team/Snoke.git

addons:
    sonarcloud:
        organization: "echo-team"
        token:
            secure: $SONAR_TOKEN
    apt:
        packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

script:
    - qmake
    - make -j
    - ./tests/tests

after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all -j
    - sonar-scanner
    - cd $TRAVIS_BUILD_DIR
    - chmod +x generateDocumentationAndDeploy.sh
    - "./generateDocumentationAndDeploy.sh"


cache:
    directories:
        - '$HOME/.sonar/cache'

notifications:
    email: true
