.TH "Game" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP (int size=20, int sp=100)"
.br
.ti -1c
.RI "int \fBrun\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetSpeed\fP (int sp)"
.br
.ti -1c
.RI "bool \fBinitSnake\fP (\fBPoint\fP begin, int dir, int length)"
.br
.ti -1c
.RI "bool \fBinitBall\fP (\fBBall\fP *ball)"
.br
.ti -1c
.RI "bool \fBwipeChange\fP (\fBPoint\fP **\fBchange\fP, int size)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBspeed\fP"
.br
.ti -1c
.RI "int \fBchangeSize\fP"
.br
.ti -1c
.RI "\fBSnake\fP \fBsnake\fP"
.br
.ti -1c
.RI "\fBSnake\fP * \fBsnakeEnemies\fP"
.br
.ti -1c
.RI "\fBLabyrinth\fP \fBlabyrinth\fP"
.br
.ti -1c
.RI "\fBPoint\fP * \fBchange\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main game class 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP speed - game refresh spee(in milliseconds) 
.br
\fI{int}\fP changeSize - the size of the change sub-arrays 
.br
\fI{Snake}\fP snake - the local_player-controlled snake entity 
.br
\fI{Snake*}\fP snakeEnemies - the remotely controlled snake entities 
.br
\fI{Labyrinth}\fP labyrinth - object containing labyrinth, displaying it, etc 
.br
\fI{Point*}\fP change - 2-dim array containing changes for the labyrinth 
.RE
.PP

.PP
Definition at line 19 of file game\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Game::init (intsize = \fC20\fP, intspeed = \fC100\fP)"
Initializes game 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP size - size of the game field(size - 2 columns, size/2 - 2 rows) 
.br
\fI{int}\fP speed - speed of the game(1 / refresh rate) in milliseconds 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} - mark of successful initialization 
.RE
.PP
Initializing the change array, containing Points to be changed in the labyrinth
.PP
Definition at line 16 of file game\&.cpp\&.
.SS "bool Game::initBall (\fBBall\fP *ball)\fC [private]\fP"
\fBBall\fP initialization with labyrinth updating 
.PP
\fBParameters:\fP
.RS 4
\fI{Ball*}\fP ball - a pointer to a \fBBall\fP, which is being initialized 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} - mark of succesful initialization 
.RE
.PP

.PP
Definition at line 155 of file game\&.cpp\&.
.SS "bool Game::initSnake (\fBPoint\fPbegin, intdir, intlength)\fC [private]\fP"
\fBSnake\fP initialization with labyrinth updating 
.PP
\fBParameters:\fP
.RS 4
\fI{Point}\fP begin - starting Point of a snake(where the tail segment will be situated) 
.br
\fI{short}\fP dir - direction of snake's 'growth' as well as it's starting direction 
.br
\fI{int}\fP length - the length of a 'new born' snake 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} - mark of whether the snake is successfully initialized 
.RE
.PP

.PP
Definition at line 141 of file game\&.cpp\&.
.SS "int Game::run ()"
Main game loop 
.PP
\fBReturns:\fP
.RS 4
{int} - the exit code 
.RE
.PP
Block initializing ncurses console in the current console window, and setting some parameters
.PP
Initializing snake by giving it the starting position, direction of growth and starting length
.PP
Initializing the \fBBall\fP and generating it on the field
.PP
displaying the starting state of labyrinth
.PP
Setting the flag for the next iteration check Moving the snake and getting the Points of a labyrinth which are to be changed in change array
.PP
Updating labyrinth with change array Points and displaying/deleting added/removed Points
.PP
Definition at line 38 of file game\&.cpp\&.
.SS "void Game::setSpeed (intspeed)\fC [private]\fP"
The method to change the game speed without giving the direct access and some error handling 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP speed - speed of the game(1 / refresh rate) in milliseconds 
.RE
.PP

.PP
Definition at line 192 of file game\&.cpp\&.
.SS "bool Game::wipeChange (\fBPoint\fP **change, intsize)\fC [private]\fP"
Initialization of the change array 
.PP
\fBParameters:\fP
.RS 4
\fI{Point**}\fP change - The pointer to an array 
.br
\fI{int}\fP size - The size of array(number of elements it can contain) 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} 
.RE
.PP

.PP
Definition at line 169 of file game\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPoint\fP* Game::change[2]\fC [private]\fP"

.PP
Definition at line 27 of file game\&.h\&.
.SS "int Game::changeSize\fC [private]\fP"

.PP
Definition at line 23 of file game\&.h\&.
.SS "\fBLabyrinth\fP Game::labyrinth\fC [private]\fP"

.PP
Definition at line 26 of file game\&.h\&.
.SS "\fBSnake\fP Game::snake\fC [private]\fP"

.PP
Definition at line 24 of file game\&.h\&.
.SS "\fBSnake\fP* Game::snakeEnemies\fC [private]\fP"

.PP
Definition at line 25 of file game\&.h\&.
.SS "int Game::speed\fC [private]\fP"

.PP
Definition at line 22 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
