.TH "/home/travis/build/echo-team/Snoke/Libraries/Game/game.cpp" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/echo-team/Snoke/Libraries/Game/game.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'game\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBgameFieldSize\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBPoint\fP gameFieldSize"
gameFieldSize - a variable, which stores the dimensions of the game field(shared with snakes)  {Point}  
.PP
Definition at line 8 of file game\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
