.TH "MenuButton" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuButton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes menu button 
.PP
\fBParameters:\fP
.RS 4
\fI{const\fP char*} name - text drawn at the button 
.RE
.PP

.PP
Definition at line 12 of file menu\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* MenuButton::name"

.PP
Definition at line 14 of file menu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
