.TH "/home/travis/build/echo-team/Snoke/Libraries/SideMenu/SideMenu.h" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/echo-team/Snoke/Libraries/SideMenu/SideMenu.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSideButton\fP"
.br
.ti -1c
.RI "class \fBSideMenu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
