.TH "Widget" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Widget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.h>\fP
.PP
Inherited by \fBMenu\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBfocus\fP (int index)"
.br
.ti -1c
.RI "virtual void \fBunfocus\fP (int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic class of the console widget (to store different widgets in one list) 
.PP
Definition at line 7 of file interface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Widget::focus (intindex)\fC [virtual]\fP"
Event listener activated by \fBNavigator\fP module when user selects widget   Navigator::listener 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP index - index of subunit of the widget 
.RE
.PP

.PP
Reimplemented in \fBMenu\fP\&.
.PP
Definition at line 9 of file interface\&.cpp\&.
.SS "void Widget::unfocus (intindex)\fC [virtual]\fP"
Event listener activated by \fBNavigator\fP module when user clicks on widget   Navigator::listener 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP index - index of subunit of the widget 
.RE
.PP

.PP
Reimplemented in \fBMenu\fP\&.
.PP
Definition at line 18 of file interface\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
