.TH "_PointStyle" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PointStyle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_PointStyle\fP & \fBoperator=\fP (\fB_PointStyle\fP ps)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBletter\fP"
.br
.ti -1c
.RI "int \fBfg\fP"
.br
.ti -1c
.RI "int \fBbg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Style of the cell in console window 
.PP
\fBParameters:\fP
.RS 4
\fI{char}\fP letter - symbol in the cell 
.br
\fI{short}\fP fg - foreground color of the cell 
.br
\fI{short}\fP bg - beckground color of the cell 
.RE
.PP

.PP
Definition at line 26 of file common\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPointStyle\fP & PointStyle::operator= (\fB_PointStyle\fP ps)"
Operation '=' override for the PointStyle type 
.PP
\fBParameters:\fP
.RS 4
\fI{PointStyle}\fP ps - the obgect, parameters of which are being copied @retrun {PointStyle&} a pointer to an object @override 
.RE
.PP

.PP
Definition at line 9 of file common\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int _PointStyle::bg"

.PP
Definition at line 29 of file common\&.h\&.
.SS "int _PointStyle::fg"

.PP
Definition at line 29 of file common\&.h\&.
.SS "char _PointStyle::letter"

.PP
Definition at line 28 of file common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
