.TH "Libraries/Common/common.cpp" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libraries/Common/common.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fBPoint\fP p1, \fBPoint\fP p2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &s, \fBPoint\fP p)"
.br
.ti -1c
.RI "void \fBmSleep\fP (int time)"
.br
.ti -1c
.RI "bool \fBinAddChange\fP (\fBPoint\fP p, \fBPoint\fP *change[2], int changeSize)"
.br
.ti -1c
.RI "bool \fBinRemChange\fP (\fBPoint\fP p, \fBPoint\fP *change[2], int changeSize)"
.br
.ti -1c
.RI "\fBPoint\fP \fBgetConsoleSize\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPoint\fP getConsoleSize ()"
Gets size of current console screen in symdols 
.PP
\fBReturns:\fP
.RS 4
{Point} size 
.RE
.PP

.PP
Definition at line 116 of file common\&.cpp\&.
.SS "bool inAddChange (\fBPoint\fP p, \fBPoint\fP * change[2], int changeSize)"
Check if Points is in the addition queue 
.PP
\fBParameters:\fP
.RS 4
\fI{Point}\fP p - point to check 
.br
\fI{Point*[2]}\fP change - array of changed Points 
.br
\fI{int}\fP changeSize - size of the change array 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} 
.RE
.PP

.PP
Definition at line 81 of file common\&.cpp\&.
.SS "bool inRemChange (\fBPoint\fP p, \fBPoint\fP * change[2], int changeSize)"
Check if the Point is in the remove queue 
.PP
\fBParameters:\fP
.RS 4
\fI{Point}\fP p - point to check 
.br
\fI{Point*[2]}\fP change - array of changed Points 
.br
\fI{int}\fP changeSize - size of the change array 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} 
.RE
.PP

.PP
Definition at line 100 of file common\&.cpp\&.
.SS "void mSleep (int time)"
Cross-platform sleep function cover 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP time - time the game will 'freeze' for in milliseconds 
.RE
.PP

.PP
Definition at line 60 of file common\&.cpp\&.
.SS "std::ostream& operator<< (std::ostream & s, \fBPoint\fP p)"
Operation '<<' override for the Point type 
.PP
\fBParameters:\fP
.RS 4
\fI{std::ostream&}\fP s - current ostream variable 
.br
\fI{Point}\fP p - a Point to print 
.RE
.PP
\fBReturns:\fP
.RS 4
{std::ostream&} @override 
.RE
.PP

.PP
Definition at line 50 of file common\&.cpp\&.
.SS "bool operator== (\fBPoint\fP p1, \fBPoint\fP p2)"
Operation '==' override for the Point type 
.PP
\fBParameters:\fP
.RS 4
\fI{Point}\fP p1 - The first Point 
.br
\fI{Point}\fP p2 - The second Point 
.RE
.PP
\fBReturns:\fP
.RS 4
{bool} @override 
.RE
.PP

.PP
Definition at line 38 of file common\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
