.TH "Libraries/Game/game.h" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libraries/Game/game.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Snake/snake\&.h'\fP
.br
\fC#include '\&.\&./Labyrinth/labyrinth\&.h'\fP
.br
\fC#include <ncurses\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
