.TH "MainMenu" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainMenu\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main menu class 
.PP
Definition at line 11 of file mainMenu\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void MainMenu::draw ()"
Draws main menu 
.PP
Definition at line 6 of file mainMenu\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
