.TH "Main.cpp" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include 'Libraries/Screens/mainMenu\&.h'\fP
.br
\fC#include 'Libraries/Game/game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 5 of file Main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
