.TH "md__r_e_a_d_m_e" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- What is Snoke? 
An extended version of the console game called 'Snake'\&. 
.SS "Warm memories"
.PP
This game will provide you a lot of oldschool fun and nostalgy\&. Collect your friends, create a team and fight another teams and organisations\&. 
.SS "Justice"
.PP
Shoke is a new way of solving argues\&. Just stand the idea and see how many people are ready to defend it! 
.SS "Arcade"
.PP
Designed for people who trying to cope with waiting\&. Play the arcade mod while your npm installing packs! 
