.TH "Menu" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.PP
Inherits \fBWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddButton\fP (const char *name)"
.br
.ti -1c
.RI "void \fBfocus\fP (int index)"
.br
.ti -1c
.RI "void \fBunfocus\fP (int index)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "\fBMenu\fP (int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBMenuButton\fP > \fBbuttons\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMenu\fP (list of selestable items) widget class 
.PP
\fBParameters:\fP
.RS 4
\fI{list<MenuButton>}\fP buttons - buttons included in menu 
.br
\fI{int}\fP x - x coordinate of left menu side 
.br
\fI{int}\fP y - y coordinate of top menu side 
.br
\fI{int}\fP width - menu width 
.br
\fI{int}\fP height - menu height 
.RE
.PP

.PP
Definition at line 25 of file menu\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Menu::Menu (int x, int y, int width, int height)"
@constructor 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP x - x coordinate of left menu side 
.br
\fI{int}\fP y - y coordinate of top menu side 
.br
\fI{int}\fP width - menu width 
.br
\fI{int}\fP height - menu height 
.RE
.PP

.PP
Definition at line 58 of file menu\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Menu::addButton (const char * name)"
Adds button to the menu 
.PP
\fBParameters:\fP
.RS 4
\fI{const\fP char*} name - text drawn at the button 
.RE
.PP

.PP
Definition at line 7 of file menu\&.cpp\&.
.SS "void Menu::draw ()"
Draws \fBMenu\fP in console window 
.PP
Definition at line 39 of file menu\&.cpp\&.
.SS "void Menu::focus (int index)\fC [virtual]\fP"
Event listener activated by \fBNavigator\fP module when user selects on widget @override @callback Navigator::listener 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP index - index of subunit of the widget 
.RE
.PP

.PP
Reimplemented from \fBWidget\fP\&.
.PP
Definition at line 18 of file menu\&.cpp\&.
.SS "void Menu::unfocus (int index)\fC [virtual]\fP"
Event listener activated by \fBNavigator\fP module when user removes selection from widget @override @callback Navigator::listener 
.PP
\fBParameters:\fP
.RS 4
\fI{int}\fP index - index of subunit of the widget 
.RE
.PP

.PP
Reimplemented from \fBWidget\fP\&.
.PP
Definition at line 30 of file menu\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::list<\fBMenuButton\fP> Menu::buttons\fC [private]\fP"

.PP
Definition at line 28 of file menu\&.h\&.
.SS "int Menu::height\fC [private]\fP"

.PP
Definition at line 29 of file menu\&.h\&.
.SS "int Menu::width\fC [private]\fP"

.PP
Definition at line 29 of file menu\&.h\&.
.SS "int Menu::x\fC [private]\fP"

.PP
Definition at line 29 of file menu\&.h\&.
.SS "int Menu::y\fC [private]\fP"

.PP
Definition at line 29 of file menu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
