.TH "Libraries/Interface/menu.h" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libraries/Interface/menu.h
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'interface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMenuButton\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
