.TH "SideMenu" 3 "Thu May 2 2019" "Snoke" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SideMenu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SideMenu\&.h>\fP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "list< \fBSideButton\fP > \fBbuttons\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file SideMenu\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "list<\fBSideButton\fP> SideMenu::buttons\fC [private]\fP"

.PP
Definition at line 14 of file SideMenu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Snoke from the source code\&.
